import "server-only";

import type {
  CityImageryAsset,
  CityIssueAnalysis,
  CityMonitorCityConfig,
  CitySimulationMetadata,
} from "@/lib/city-monitor/types";

/**
 * A deterministic, server-created observation for demonstrations and judging.
 * It is deliberately not a KartaView photo and has no external image URL.
 */
export const DEMONSTRATION_SCENARIO_ID = "lucknow-water-filled-pothole-001";
export const DEMONSTRATION_SCENARIO_LABEL = "Simulated water-filled pothole detection";

export type DemonstrationDetectionEvent = {
  eventId: string;
  cityId: string;
  source: "DEMONSTRATION_SIMULATION";
  scenario: CitySimulationMetadata;
  asset: CityImageryAsset;
};

export function createDemonstrationDetectionEvent(
  city: CityMonitorCityConfig
): DemonstrationDetectionEvent {
  const generatedAt = new Date().toISOString();
  const scenario: CitySimulationMetadata = {
    scenarioId: DEMONSTRATION_SCENARIO_ID,
    label: DEMONSTRATION_SCENARIO_LABEL,
    generatedAt,
  };

  // The coordinates are intentionally close to the configured city center and
  // are marked as simulated metadata; they do not assert a real observation.
  const asset: CityImageryAsset = {
    provider: "demonstration",
    providerPhotoId: DEMONSTRATION_SCENARIO_ID,
    providerSequenceId: null,
    sequenceIndex: null,
    imageUrl: `simulation://jalsarthi/${city.id}/${DEMONSTRATION_SCENARIO_ID}`,
    latitude: Number((city.center.latitude + 0.0007).toFixed(6)),
    longitude: Number((city.center.longitude + 0.0005).toFixed(6)),
    heading: null,
    capturedAt: null,
    addedAt: null,
    processedAt: null,
    discoveredAt: generatedAt,
    visibility: "simulation",
    status: "generated",
    qualityLevel: null,
    processingStatus: "simulation_ready",
    simulation: scenario,
  };

  return {
    eventId: `demo-event:${DEMONSTRATION_SCENARIO_ID}`,
    cityId: city.id,
    source: "DEMONSTRATION_SIMULATION",
    scenario,
    asset,
  };
}

export function analyzeDemonstrationAsset(asset: CityImageryAsset): CityIssueAnalysis {
  if (asset.provider !== "demonstration" || !asset.simulation) {
    throw new Error("A demonstration analysis requires a demonstration asset.");
  }

  return {
    detected: true,
    category: "WATER_FILLED_POTHOLE",
    confidence: 0.96,
    description:
      "Demonstration detection: a road pothole containing standing water is flagged for review.",
    evidence: [
      "Standing water is visibly contained within a road-surface depression.",
      "The depression is positioned within the vehicle travel area.",
      "The structured result is generated by the controlled demonstration scenario.",
    ],
  };
}
